In [299]:
import pandas as pd

In [300]:
df_1 = pd.read_csv("Ford_Mondeo.csv")
df_1.drop('name', inplace=True, axis=1)
df_1.insert(1, 'Name', 'Ford Mondeo')
df_1

                                                   link         Name    price   mileage    BHP transmission           fuel  owners       body  ULEZ engine           year
0     https://www.autotrader.co.uk/dealers/essex/rom...  Ford Mondeo   £1,795  149026.0  153.0       Manual         Diesel     2.0     Saloon   NaN   2.2L  2005 (55 reg)
1     https://www.autotrader.co.uk/dealers/bedfordsh...  Ford Mondeo   £2,499  102000.0  224.0       Manual         Petrol     NaN  Hatchback  ULEZ   3.0L  2005 (05 reg)
2                          https://www.autotrader.co.uk  Ford Mondeo     £995  109299.0  123.0       Manual         Petrol     2.0     Saloon   NaN   1.8L  2005 (05 reg)
3     https://www.autotrader.co.uk/dealers/west-midl...  Ford Mondeo   £1,295   75500.0  123.0       Manual         Petrol     NaN     Estate   NaN   1.8L  2005 (55 reg)
4                          https://www.autotrader.co.uk  Ford Mondeo   £1,750  157390.0  153.0       Manual         Diesel     2.0     Estate   NaN   2.2L  2005 (05 reg)
...                                                 ...          ...      ...       ...    ...          ...            ...     ...        ...   ...    ...            ...
1637  https://www.autotrader.co.uk/dealers/merseysid...  Ford Mondeo  £31,625    5567.0    NaN    Automatic  Petrol Hybrid     NaN     Estate  ULEZ   2.0L  2021 (71 reg)
1638  https://www.autotrader.co.uk/dealers/north-yor...  Ford Mondeo  £29,995    8150.0    NaN    Automatic  Petrol Hybrid     NaN     Estate  ULEZ   2.0L  2021 (70 reg)
1639  https://www.autotrader.co.uk/dealers/north-yor...  Ford Mondeo  £29,999   12435.0    NaN    Automatic  Petrol Hybrid     NaN     Estate  ULEZ   2.0L  2021 (71 reg)
1640  https://www.autotrader.co.uk/dealers/cleveland...  Ford Mondeo  £26,999   15461.0    NaN    Automatic  Petrol Hybrid     NaN     Estate  ULEZ   2.0L  2021 (21 reg)
1641  https://www.autotrader.co.uk/dealers/suffolk/i...  Ford Mondeo  £28,995   17705.0    NaN    Automatic  Petrol Hybrid     NaN     Estate  ULEZ   2.0L  2021 (21 reg)

[1642 rows x 12 columns]

In [301]:
df_2 = pd.read_csv("Ford_ecosport.csv")
df_2.drop('name', inplace=True, axis=1)
df_2.insert(1, 'Name', 'Ford Ecosport')
df_2

                                                   link           Name    price  mileage  BHP transmission    fuel  owners body  ULEZ engine           year
0     https://www.autotrader.co.uk/dealers/surrey/ca...  Ford Ecosport   £6,990  48000.0  NaN       Manual  Petrol     NaN  SUV  ULEZ   1.0L  2014 (63 reg)
1     https://www.autotrader.co.uk/dealers/berkshire...  Ford Ecosport   £7,000  68000.0  NaN       Manual  Diesel     NaN  SUV   NaN   1.5L  2014 (64 reg)
2     https://www.autotrader.co.uk/dealers/hertfords...  Ford Ecosport   £7,500  47000.0  NaN       Manual  Petrol     3.0  SUV  ULEZ   1.0L  2014 (14 reg)
3                          https://www.autotrader.co.uk  Ford Ecosport   £6,200  63000.0  NaN       Manual  Diesel     2.0  SUV   NaN   1.5L  2014 (64 reg)
4     https://www.autotrader.co.uk/dealers/bedfordsh...  Ford Ecosport   £6,490  74000.0  NaN       Manual  Diesel     2.0  SUV   NaN   1.5L  2014 (64 reg)
...                                                 ...            ...      ...      ...  ...          ...     ...     ...  ...   ...    ...            ...
1943  https://www.autotrader.co.uk/dealers/tyne-wear...  Ford Ecosport  £16,999   6351.0  NaN       Manual  Petrol     NaN  SUV  ULEZ   1.0L  2021 (21 reg)
1944  https://www.autotrader.co.uk/dealers/fife/dunf...  Ford Ecosport  £19,400   6002.0  NaN       Manual  Petrol     NaN  SUV  ULEZ   1.0L  2021 (21 reg)
1945  https://www.autotrader.co.uk/dealers/aberdeens...  Ford Ecosport  £19,800   4678.0  NaN       Manual  Petrol     NaN  SUV  ULEZ   1.0L  2021 (71 reg)
1946  https://www.autotrader.co.uk/dealers/norwich/h...  Ford Ecosport  £21,490   2200.0  NaN       Manual  Petrol     NaN  SUV  ULEZ   1.0L  2021 (70 reg)
1947  https://www.autotrader.co.uk/dealers/north-yor...  Ford Ecosport  £18,995   9103.0  NaN       Manual  Petrol     NaN  SUV  ULEZ   1.0L  2021 (21 reg)

[1948 rows x 12 columns]

In [302]:
df_3 = pd.read_csv("Ford_C-max(2).csv")
df_3.drop('name', inplace=True, axis=1)
df_3.insert(1, 'Name', 'Ford C-Max')
df_3

                                                   link        Name    price   mileage    BHP transmission    fuel  owners body  ULEZ engine           year
0                          https://www.autotrader.co.uk  Ford C-Max   £1,575  109950.0  134.0       Manual  Diesel     NaN  MPV   NaN   2.0L  2006 (56 reg)
1     https://www.autotrader.co.uk/dealers/greater-l...  Ford C-Max   £1,695  100326.0   99.0       Manual  Petrol     3.0  MPV  ULEZ   1.6L  2007 (07 reg)
2     https://www.autotrader.co.uk/dealers/bedfordsh...  Ford C-Max   £2,100   96830.0  123.0       Manual  Petrol     6.0  MPV  ULEZ   1.8L  2007 (57 reg)
3                          https://www.autotrader.co.uk  Ford C-Max   £1,450  113129.0  143.0       Manual  Petrol     6.0  MPV  ULEZ   2.0L  2007 (07 reg)
4     https://www.autotrader.co.uk/dealers/hampshire...  Ford C-Max   £1,699  142000.0  108.0       Manual  Diesel     3.0  MPV   NaN   1.6L  2007 (57 reg)
...                                                 ...         ...      ...       ...    ...          ...     ...     ...  ...   ...    ...            ...
1221  https://www.autotrader.co.uk/dealers/kent/well...  Ford C-Max  £18,495   11345.0    NaN    Automatic  Petrol     NaN  MPV  ULEZ   1.5L  2019 (19 reg)
1222  https://www.autotrader.co.uk/dealers/kent/well...  Ford C-Max  £16,995    8500.0    NaN    Automatic  Petrol     NaN  MPV  ULEZ   1.5L  2019 (19 reg)
1223  https://www.autotrader.co.uk/dealers/kent/well...  Ford C-Max  £16,995   13000.0    NaN    Automatic  Petrol     NaN  MPV  ULEZ   1.5L  2019 (68 reg)
1224  https://www.autotrader.co.uk/dealers/essex/rai...  Ford C-Max  £15,400   11214.0    NaN    Automatic  Diesel     NaN  MPV  ULEZ   2.0L  2020 (69 reg)
1225  https://www.autotrader.co.uk/dealers/cheshire/...  Ford C-Max  £12,995   16625.0    NaN       Manual  Diesel     2.0  MPV  ULEZ   1.5L  2020 (17 reg)

[1226 rows x 12 columns]

In [303]:
df_4 = pd.read_csv("Ford_Kuga.csv")
df_4.drop('name', inplace=True, axis=1)
df_4.insert(1, 'Name', 'Ford Kuga')
df_4

                                                   link       Name    price   mileage    BHP transmission                   fuel  owners body  ULEZ engine           year
0                          https://www.autotrader.co.uk  Ford Kuga   £2,350  140000.0    NaN       Manual                 Diesel     NaN  SUV   NaN   2.0L  2008 (58 reg)
1                          https://www.autotrader.co.uk  Ford Kuga   £2,800  147000.0    NaN       Manual                 Diesel     4.0  SUV   NaN   2.0L  2008 (58 reg)
2     https://www.autotrader.co.uk/dealers/essex/ray...  Ford Kuga   £3,995  121000.0  134.0       Manual                 Diesel     NaN  SUV   NaN   2.0L  2008 (08 reg)
3     https://www.autotrader.co.uk/dealers/berkshire...  Ford Kuga   £4,400   92000.0    NaN       Manual                 Diesel     NaN  SUV   NaN   2.0L  2008 (58 reg)
4     https://www.autotrader.co.uk/dealers/west-midl...  Ford Kuga   £3,499  123000.0    NaN       Manual                 Diesel     NaN  SUV   NaN   2.0L  2008 (58 reg)
...                                                 ...        ...      ...       ...    ...          ...                    ...     ...  ...   ...    ...            ...
4663  https://www.autotrader.co.uk/dealers/county-an...  Ford Kuga  £32,890    6638.0    NaN    Automatic  Petrol Plug-in Hybrid     NaN  SUV  ULEZ   2.5L            NaN
4664  https://www.autotrader.co.uk/dealers/county-an...  Ford Kuga  £32,495    7017.0    NaN    Automatic                 Diesel     NaN  SUV  ULEZ   2.0L            NaN
4665  https://www.autotrader.co.uk/dealers/county-an...  Ford Kuga  £27,490   12232.0    NaN       Manual                 Petrol     NaN  SUV  ULEZ   1.5L            NaN
4666  https://www.autotrader.co.uk/dealers/west-midl...  Ford Kuga  £26,795    6000.0    NaN       Manual                 Diesel     NaN  SUV  ULEZ   2.0L  2021 (70 reg)
4667  https://www.autotrader.co.uk/dealers/norwich/h...  Ford Kuga  £29,990   19956.0    NaN    Automatic                 Diesel     NaN  SUV  ULEZ   2.0L  2021 (21 reg)

[4668 rows x 12 columns]

In [304]:
df_5 = pd.read_csv("Ford_Focus.csv")
df_5.drop('name', inplace=True, axis=1)
df_5.insert(1, 'Name', 'Ford Focus')
df_5

        price        Name  mileage    BHP transmission    fuel  owners       body  ULEZ engine           year
0      �2,200  Ford Focus    65000   79.0       Manual  Petrol     NaN  Hatchback  ULEZ   1.4L  2005 (05 reg)
1      �2,000  Ford Focus    83000   99.0       Manual  Petrol     NaN  Hatchback  ULEZ   1.6L  2005 (05 reg)
2        �995  Ford Focus   125893   99.0       Manual  Petrol     NaN     Estate  ULEZ   1.6L  2005 (05 reg)
3      �1,350  Ford Focus   118500   99.0       Manual  Petrol     NaN  Hatchback  ULEZ   1.6L  2005 (05 reg)
4      �1,499  Ford Focus    97000  113.0       Manual  Petrol     NaN  Hatchback  ULEZ   1.6L  2005 (05 reg)
...       ...         ...      ...    ...          ...     ...     ...        ...   ...    ...            ...
8280  �10,495  Ford Focus    63227  221.0       Manual  Petrol     6.0  Hatchback  ULEZ   2.5L            NaN
8281  �46,000  Ford Focus     5731  301.0       Manual  Petrol     NaN  Hatchback  ULEZ   2.5L            NaN
8282  �39,995  Ford Focus    14000  301.0       Manual  Petrol     4.0  Hatchback  ULEZ   2.5L            NaN
8283  �34,995  Ford Focus    35264  301.0       Manual  Petrol     NaN  Hatchback  ULEZ   2.5L            NaN
8284  �28,995  Ford Focus    70000  301.0       Manual  Petrol     5.0  Hatchback  ULEZ   2.5L            NaN

[8285 rows x 11 columns]

In [305]:
df_6 = pd.read_csv("Ford_Fiesta.csv")
df_6.drop('name', inplace=True, axis=1)
df_6.insert(1, 'Name', 'Ford Fiesta')
df_6

         price         Name   mileage   BHP transmission    fuel  owners       body  ULEZ engine           year
0      �10,000  Ford Fiesta   26200.0   NaN       Manual  Petrol     2.0  Hatchback  ULEZ   1.0L  2015 (65 reg)
1      �10,000  Ford Fiesta   24000.0   NaN       Manual  Petrol     NaN  Hatchback  ULEZ   1.0L  2016 (66 reg)
2      �10,000  Ford Fiesta   26780.0   NaN       Manual  Petrol     NaN  Hatchback  ULEZ   1.0L  2016 (16 reg)
3      �10,000  Ford Fiesta   45000.0   NaN    Automatic  Petrol     NaN  Hatchback  ULEZ   1.0L  2016 (65 reg)
4      �10,000  Ford Fiesta   16261.0   NaN       Manual  Petrol     NaN  Hatchback  ULEZ   1.0L  2016 (16 reg)
...        ...          ...       ...   ...          ...     ...     ...        ...   ...    ...            ...
9997      �995  Ford Fiesta  119000.0  74.0       Manual  Petrol     8.0  Hatchback  ULEZ    NaN  2006 (06 reg)
9998      �995  Ford Fiesta  100000.0  74.0       Manual  Petrol     8.0  Hatchback  ULEZ    NaN  2007 (57 reg)
9999      �995  Ford Fiesta  127578.0  74.0       Manual  Petrol     4.0  Hatchback  ULEZ    NaN  2007 (07 reg)
10000     �995  Ford Fiesta  105775.0  74.0       Manual  Petrol     3.0  Hatchback  ULEZ    NaN  2008 (57 reg)
10001     �999  Ford Fiesta   91000.0  74.0       Manual  Petrol     NaN  Hatchback  ULEZ    NaN  2005 (05 reg)

[10002 rows x 11 columns]

In [306]:
df_7 = pd.read_csv("Ford_Puma.csv")
df_7.drop('name', inplace=True, axis=1)
df_7.insert(1, 'Name', 'Ford Puma')
df_7

                                                   link       Name    price  mileage  BHP transmission           fuel  owners body  ULEZ engine           year
0     https://www.autotrader.co.uk/dealers/essex/bar...  Ford Puma  £18,900  11769.0  NaN       Manual         Petrol     NaN  SUV  ULEZ   1.0L  2019 (69 reg)
1     https://www.autotrader.co.uk/dealers/suffolk/h...  Ford Puma  £20,750  19363.0  NaN       Manual         Petrol     2.0  SUV  ULEZ   1.0L  2019 (69 reg)
2     https://www.autotrader.co.uk/dealers/london/me...  Ford Puma  £19,000  16657.0  NaN       Manual         Petrol     NaN  SUV  ULEZ   1.0L  2019 (69 reg)
3     https://www.autotrader.co.uk/dealers/middlesex...  Ford Puma  £20,100  15879.0  NaN       Manual         Petrol     NaN  SUV  ULEZ   1.0L  2019 (69 reg)
4     https://www.autotrader.co.uk/dealers/middlesex...  Ford Puma  £18,990  15000.0  NaN       Manual         Petrol     2.0  SUV  ULEZ   1.0L  2020 (70 reg)
...                                                 ...        ...      ...      ...  ...          ...            ...     ...  ...   ...    ...            ...
1723  https://www.autotrader.co.uk/dealers/suffolk/s...  Ford Puma  £19,990   8200.0  NaN       Manual  Petrol Hybrid     NaN  SUV  ULEZ   1.0L  2021 (71 reg)
1724  https://www.autotrader.co.uk/dealers/norwich/h...  Ford Puma  £28,990    300.0  NaN    Automatic         Petrol     NaN  SUV  ULEZ   1.0L  2021 (71 reg)
1725  https://www.autotrader.co.uk/dealers/staffords...  Ford Puma  £26,999   6300.0  NaN       Manual         Petrol     NaN  SUV  ULEZ   1.5L  2021 (70 reg)
1726  https://www.autotrader.co.uk/dealers/suffolk/s...  Ford Puma  £19,690  13251.0  NaN       Manual         Petrol     NaN  SUV  ULEZ   1.0L  2021 (21 reg)
1727  https://www.autotrader.co.uk/dealers/county-an...  Ford Puma  £21,995  19000.0  NaN       Manual         Petrol     NaN  SUV  ULEZ   1.0L            NaN

[1728 rows x 12 columns]

In [307]:
df_8 = pd.read_csv("Ford_Ranger.csv")
df_8.drop('name', inplace=True, axis=1)
df_8.insert(1, 'Name', 'Ford Ranger')
df_8

                                                   link         Name    price   mileage    BHP transmission    fuel  owners    body  ULEZ engine           year
0                          https://www.autotrader.co.uk  Ford Ranger   £5,495   77500.0  107.0       Manual  Diesel     NaN  Pickup   NaN   2.5L  2005 (55 reg)
1     https://www.autotrader.co.uk/dealers/west-york...  Ford Ranger   £3,995  145000.0  107.0       Manual  Diesel     NaN  Pickup   NaN   2.5L  2005 (05 reg)
2                          https://www.autotrader.co.uk  Ford Ranger   £5,991   98000.0  107.0       Manual  Diesel     NaN  Pickup   NaN   2.5L  2006 (06 reg)
3     https://www.autotrader.co.uk/dealers/bedfordsh...  Ford Ranger   £7,945   58000.0  107.0       Manual  Diesel     NaN  Pickup   NaN   2.5L  2006 (56 reg)
4                          https://www.autotrader.co.uk  Ford Ranger   £5,995   95900.0  107.0       Manual  Diesel     2.0  Pickup   NaN   2.5L  2006 (06 reg)
...                                                 ...          ...      ...       ...    ...          ...     ...     ...     ...   ...    ...            ...
1982  https://www.autotrader.co.uk/dealers/glamorgan...  Ford Ranger  £32,995    5513.0    NaN    Automatic  Diesel     3.0  Pickup  ULEZ   2.0L  2021 (21 reg)
1983  https://www.autotrader.co.uk/dealers/cambridge...  Ford Ranger  £39,594    9900.0    NaN    Automatic  Diesel     NaN  Pickup  ULEZ   2.0L  2021 (70 reg)
1984  https://www.autotrader.co.uk/dealers/hampshire...  Ford Ranger  £35,940   15000.0  210.0    Automatic  Diesel     NaN  Pickup  ULEZ   2.0L  2021 (70 reg)
1985  https://www.autotrader.co.uk/dealers/herefords...  Ford Ranger  £35,994    6228.0    NaN    Automatic  Diesel     2.0  Pickup  ULEZ   2.0L  2021 (21 reg)
1986                       https://www.autotrader.co.uk  Ford Ranger  £32,800   31500.0    NaN    Automatic  Diesel     4.0  Pickup  ULEZ   2.0L  2021 (21 reg)

[1987 rows x 12 columns]

In [308]:
df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8])
df

                                                   link         Name    price   mileage    BHP transmission    fuel  owners       body  ULEZ engine           year
0     https://www.autotrader.co.uk/dealers/essex/rom...  Ford Mondeo   £1,795  149026.0  153.0       Manual  Diesel     2.0     Saloon   NaN   2.2L  2005 (55 reg)
1     https://www.autotrader.co.uk/dealers/bedfordsh...  Ford Mondeo   £2,499  102000.0  224.0       Manual  Petrol     NaN  Hatchback  ULEZ   3.0L  2005 (05 reg)
2                          https://www.autotrader.co.uk  Ford Mondeo     £995  109299.0  123.0       Manual  Petrol     2.0     Saloon   NaN   1.8L  2005 (05 reg)
3     https://www.autotrader.co.uk/dealers/west-midl...  Ford Mondeo   £1,295   75500.0  123.0       Manual  Petrol     NaN     Estate   NaN   1.8L  2005 (55 reg)
4                          https://www.autotrader.co.uk  Ford Mondeo   £1,750  157390.0  153.0       Manual  Diesel     2.0     Estate   NaN   2.2L  2005 (05 reg)
...                                                 ...          ...      ...       ...    ...          ...     ...     ...        ...   ...    ...            ...
1982  https://www.autotrader.co.uk/dealers/glamorgan...  Ford Ranger  £32,995    5513.0    NaN    Automatic  Diesel     3.0     Pickup  ULEZ   2.0L  2021 (21 reg)
1983  https://www.autotrader.co.uk/dealers/cambridge...  Ford Ranger  £39,594    9900.0    NaN    Automatic  Diesel     NaN     Pickup  ULEZ   2.0L  2021 (70 reg)
1984  https://www.autotrader.co.uk/dealers/hampshire...  Ford Ranger  £35,940   15000.0  210.0    Automatic  Diesel     NaN     Pickup  ULEZ   2.0L  2021 (70 reg)
1985  https://www.autotrader.co.uk/dealers/herefords...  Ford Ranger  £35,994    6228.0    NaN    Automatic  Diesel     2.0     Pickup  ULEZ   2.0L  2021 (21 reg)
1986                       https://www.autotrader.co.uk  Ford Ranger  £32,800   31500.0    NaN    Automatic  Diesel     4.0     Pickup  ULEZ   2.0L  2021 (21 reg)

[31486 rows x 12 columns]

In [309]:
df.drop(columns=['link'], inplace = True)

In [310]:
df1= df.reset_index(drop=True)

In [311]:
df1.drop(columns=['BHP'], inplace = True)
df1

              Name    price   mileage transmission    fuel  owners       body  ULEZ engine           year
0      Ford Mondeo   £1,795  149026.0       Manual  Diesel     2.0     Saloon   NaN   2.2L  2005 (55 reg)
1      Ford Mondeo   £2,499  102000.0       Manual  Petrol     NaN  Hatchback  ULEZ   3.0L  2005 (05 reg)
2      Ford Mondeo     £995  109299.0       Manual  Petrol     2.0     Saloon   NaN   1.8L  2005 (05 reg)
3      Ford Mondeo   £1,295   75500.0       Manual  Petrol     NaN     Estate   NaN   1.8L  2005 (55 reg)
4      Ford Mondeo   £1,750  157390.0       Manual  Diesel     2.0     Estate   NaN   2.2L  2005 (05 reg)
...            ...      ...       ...          ...     ...     ...        ...   ...    ...            ...
31481  Ford Ranger  £32,995    5513.0    Automatic  Diesel     3.0     Pickup  ULEZ   2.0L  2021 (21 reg)
31482  Ford Ranger  £39,594    9900.0    Automatic  Diesel     NaN     Pickup  ULEZ   2.0L  2021 (70 reg)
31483  Ford Ranger  £35,940   15000.0    Automatic  Diesel     NaN     Pickup  ULEZ   2.0L  2021 (70 reg)
31484  Ford Ranger  £35,994    6228.0    Automatic  Diesel     2.0     Pickup  ULEZ   2.0L  2021 (21 reg)
31485  Ford Ranger  £32,800   31500.0    Automatic  Diesel     4.0     Pickup  ULEZ   2.0L  2021 (21 reg)

[31486 rows x 10 columns]

In [312]:
df1.count()

Name            31486
price           31486
mileage         31476
transmission    31475
fuel            31480
owners          10784
body            31403
ULEZ            27125
engine          29503
year            30974
dtype: int64

In [313]:
df1 = df1.dropna(subset=['transmission', 'fuel', 'body'])
df1

              Name    price   mileage transmission    fuel  owners       body  ULEZ engine           year
0      Ford Mondeo   £1,795  149026.0       Manual  Diesel     2.0     Saloon   NaN   2.2L  2005 (55 reg)
1      Ford Mondeo   £2,499  102000.0       Manual  Petrol     NaN  Hatchback  ULEZ   3.0L  2005 (05 reg)
2      Ford Mondeo     £995  109299.0       Manual  Petrol     2.0     Saloon   NaN   1.8L  2005 (05 reg)
3      Ford Mondeo   £1,295   75500.0       Manual  Petrol     NaN     Estate   NaN   1.8L  2005 (55 reg)
4      Ford Mondeo   £1,750  157390.0       Manual  Diesel     2.0     Estate   NaN   2.2L  2005 (05 reg)
...            ...      ...       ...          ...     ...     ...        ...   ...    ...            ...
31481  Ford Ranger  £32,995    5513.0    Automatic  Diesel     3.0     Pickup  ULEZ   2.0L  2021 (21 reg)
31482  Ford Ranger  £39,594    9900.0    Automatic  Diesel     NaN     Pickup  ULEZ   2.0L  2021 (70 reg)
31483  Ford Ranger  £35,940   15000.0    Automatic  Diesel     NaN     Pickup  ULEZ   2.0L  2021 (70 reg)
31484  Ford Ranger  £35,994    6228.0    Automatic  Diesel     2.0     Pickup  ULEZ   2.0L  2021 (21 reg)
31485  Ford Ranger  £32,800   31500.0    Automatic  Diesel     4.0     Pickup  ULEZ   2.0L  2021 (21 reg)

[31389 rows x 10 columns]

#

In [314]:
engines = df1.groupby('engine').count()
engines

         Name  price  mileage  transmission   fuel  owners   body   ULEZ   year
engine
1.0L    11521  11521    11519         11521  11521    2746  11521  11480  11353
1.1L      440    440      440           440    440      93    440    440    438
1.2L      295    295      295           295    295     126    295    287    294
1.4L      893    893      893           893    893     513    893    711    891
1.5L     4936   4936     4936          4936   4936    1305   4936   4739   4825
1.6L     3558   3558     3556          3558   3558    2005   3558   2252   3523
1.8L      285    285      285           285    285     172    285    161    284
2.0L     5369   5369     5366          5369   5369    2020   5369   4003   5262
2.2L      365    365      364           365    365     173    365     47    358
2.3L      241    241      241           241    241      78    241    240    233
2.5L      546    546      546           546    546     162    546    517    535
3.0L       17     17       17            17     17       8     17     11     17
3.2L      945    945      945           945    945     367    945    216    916

In [315]:

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [316]:
models= df1.groupby("Name").agg(list)
models

                                                           price                                            mileage                                       transmission                                               fuel                                             owners                                               body                                               ULEZ                                             engine                                               year
Name
Ford C-Max     [£1,575, £1,695, £2,100, £1,450, £1,699, £1,49...  [109950.0, 100326.0, 96830.0, 113129.0, 142000...  [Manual, Manual, Manual, Manual, Manual, Manua...  [Diesel, Petrol, Petrol, Petrol, Diesel, Petro...  [nan, 3.0, 6.0, 6.0, 3.0, 6.0, nan, 2.0, 2.0, ...  [MPV, MPV, MPV, MPV, MPV, MPV, MPV, MPV, MPV, ...  [nan, ULEZ, ULEZ, ULEZ, nan, ULEZ, ULEZ, ULEZ,...  [2.0L, 1.6L, 1.8L, 2.0L, 1.6L, 1.6L, 2.0L, 1.8...  [2006 (56 reg), 2007 (07 reg), 2007 (57 reg), ...
Ford Ecosport  [£6,990, £7,000, £7,500, £6,200, £6,490, £7,28...  [48000.0, 68000.0, 47000.0, 63000.0, 74000.0, ...  [Manual, Manual, Manual, Manual, Manual, Manua...  [Petrol, Diesel, Petrol, Diesel, Diesel, Petro...  [nan, nan, 3.0, 2.0, 2.0, 2.0, 2.0, nan, 3.0, ...  [SUV, SUV, SUV, SUV, SUV, SUV, SUV, SUV, SUV, ...  [ULEZ, nan, ULEZ, nan, nan, ULEZ, ULEZ, nan, n...  [1.0L, 1.5L, 1.0L, 1.5L, 1.5L, 1.5L, 1.0L, 1.5...  [2014 (63 reg), 2014 (64 reg), 2014 (14 reg), ...
Ford Fiesta    [�10,000, �10,000, �10,000, �10,000, �10,000, ...  [26200.0, 24000.0, 26780.0, 45000.0, 16261.0, ...  [Manual, Manual, Manual, Automatic, Manual, Ma...  [Petrol, Petrol, Petrol, Petrol, Petrol, Petro...  [2.0, nan, nan, nan, nan, 3.0, 2.0, nan, 2.0, ...  [Hatchback, Hatchback, Hatchback, Hatchback, H...  [ULEZ, ULEZ, ULEZ, ULEZ, ULEZ, ULEZ, ULEZ, ULE...  [1.0L, 1.0L, 1.0L, 1.0L, 1.0L, 1.0L, 1.0L, 1.0...  [2015 (65 reg), 2016 (66 reg), 2016 (16 reg), ...
Ford Focus     [�2,200, �2,000, �995, �1,350, �1,499, �1,850,...  [65000.0, 83000.0, 125893.0, 118500.0, 97000.0...  [Manual, Manual, Manual, Manual, Manual, Manua...  [Petrol, Petrol, Petrol, Petrol, Petrol, Petro...  [nan, nan, nan, nan, nan, 2.0, nan, nan, nan, ...  [Hatchback, Hatchback, Estate, Hatchback, Hatc...  [ULEZ, ULEZ, ULEZ, ULEZ, ULEZ, ULEZ, nan, nan,...  [1.4L, 1.6L, 1.6L, 1.6L, 1.6L, 1.6L, 1.6L, 1.6...  [2005 (05 reg), 2005 (05 reg), 2005 (05 reg), ...
Ford Kuga      [£2,350, £2,800, £3,995, £4,400, £3,499, £4,99...  [140000.0, 147000.0, 121000.0, 92000.0, 123000...  [Manual, Manual, Manual, Manual, Manual, Manua...  [Diesel, Diesel, Diesel, Diesel, Diesel, Diese...  [nan, 4.0, nan, nan, nan, 7.0, 4.0, nan, nan, ...  [SUV, SUV, SUV, SUV, SUV, SUV, SUV, SUV, SUV, ...  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...  [2.0L, 2.0L, 2.0L, 2.0L, 2.0L, 2.0L, 2.0L, 2.0...  [2008 (58 reg), 2008 (58 reg), 2008 (08 reg), ...
Ford Mondeo    [£1,795, £2,499, £995, £1,295, £1,750, £1,000,...  [149026.0, 102000.0, 109299.0, 75500.0, 157390...  [Manual, Manual, Manual, Manual, Manual, Manua...  [Diesel, Petrol, Petrol, Petrol, Diesel, Petro...  [2.0, nan, 2.0, nan, 2.0, 4.0, 3.0, 3.0, 4.0, ...  [Saloon, Hatchback, Saloon, Estate, Estate, Ha...  [nan, ULEZ, nan, nan, nan, ULEZ, nan, nan, nan...  [2.2L, 3.0L, 1.8L, 1.8L, 2.2L, 2.0L, 2.2L, 2.2...  [2005 (55 reg), 2005 (05 reg), 2005 (05 reg), ...
Ford Puma      [£18,900, £20,750, £19,000, £20,100, £18,990, ...  [11769.0, 19363.0, 16657.0, 15879.0, 15000.0, ...  [Manual, Manual, Manual, Manual, Manual, Manua...  [Petrol, Petrol, Petrol, Petrol, Petrol, Petro...  [nan, 2.0, nan, nan, 2.0, nan, nan, nan, nan, ...  [SUV, SUV, SUV, SUV, SUV, SUV, SUV, SUV, SUV, ...  [ULEZ, ULEZ, ULEZ, ULEZ, ULEZ, ULEZ, ULEZ, ULE...  [1.0L, 1.0L, 1.0L, 1.0L, 1.0L, 1.0L, 1.0L, 1.0...  [2019 (69 reg), 2019 (69 reg), 2019 (69 reg), ...
Ford Ranger    [£5,495, £3,995, £5,991, £7,945, £5,995, £8,49...  [77500.0, 145000.0, 98000.0, 58000.0, 95900.0,...  [Manual, Manual, Manual, Manual, Manual, Autom...  [Diesel, Diesel, Diesel, Diesel, Diesel, Diese...  [nan, nan, nan, nan, 2.0, nan, 4.0, 4.0, 5.0, ...  [Pickup, Pickup, Pickup, Pickup, Pickup, Picku...  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...  [2.5L, 2.5L, 2.5L, 2.5L, 2.5L, 3.0L, 2.5L, 2.5...  [2005 (55 reg), 2005 (05 reg), 2006 (06 reg), ...

In [317]:
df1["price"].str.replace("£","")

0         1,795
1         2,499
2           995
3         1,295
4         1,750
          ...
31481    32,995
31482    39,594
31483    35,940
31484    35,994
31485    32,800
Name: price, Length: 31389, dtype: object

In [318]:
df1.dtypes

Name             object
price            object
mileage         float64
transmission     object
fuel             object
owners          float64
body             object
ULEZ             object
engine           object
year             object
dtype: object

In [319]:
df1['Name'] = df1.Name.astype('category')
df['Name'].unique()

<ipython-input-319-dfb66d57f508>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Name'] = df1.Name.astype('category')

array(['Ford Mondeo', 'Ford Ecosport', 'Ford C-Max', 'Ford Kuga',
       'Ford Focus', 'Ford Fiesta', 'Ford Puma', 'Ford Ranger'],
      dtype=object)

In [320]:
df1["ULEZ"].fillna("Non ULEZ", inplace = True)

/Users/ramandeeprai/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [321]:
df1

              Name    price   mileage transmission    fuel  owners       body      ULEZ engine           year
0      Ford Mondeo   £1,795  149026.0       Manual  Diesel     2.0     Saloon  Non ULEZ   2.2L  2005 (55 reg)
1      Ford Mondeo   £2,499  102000.0       Manual  Petrol     NaN  Hatchback      ULEZ   3.0L  2005 (05 reg)
2      Ford Mondeo     £995  109299.0       Manual  Petrol     2.0     Saloon  Non ULEZ   1.8L  2005 (05 reg)
3      Ford Mondeo   £1,295   75500.0       Manual  Petrol     NaN     Estate  Non ULEZ   1.8L  2005 (55 reg)
4      Ford Mondeo   £1,750  157390.0       Manual  Diesel     2.0     Estate  Non ULEZ   2.2L  2005 (05 reg)
...            ...      ...       ...          ...     ...     ...        ...       ...    ...            ...
31481  Ford Ranger  £32,995    5513.0    Automatic  Diesel     3.0     Pickup      ULEZ   2.0L  2021 (21 reg)
31482  Ford Ranger  £39,594    9900.0    Automatic  Diesel     NaN     Pickup      ULEZ   2.0L  2021 (70 reg)
31483  Ford Ranger  £35,940   15000.0    Automatic  Diesel     NaN     Pickup      ULEZ   2.0L  2021 (70 reg)
31484  Ford Ranger  £35,994    6228.0    Automatic  Diesel     2.0     Pickup      ULEZ   2.0L  2021 (21 reg)
31485  Ford Ranger  £32,800   31500.0    Automatic  Diesel     4.0     Pickup      ULEZ   2.0L  2021 (21 reg)

[31389 rows x 10 columns]

In [322]:
df1.sort_values(by=['engine'])

              Name    price  mileage transmission    fuel  owners       body      ULEZ engine           year
14747   Ford Focus  �13,495  14922.0       Manual  Petrol     NaN  Hatchback      ULEZ   1.0L  2018 (18 reg)
18606  Ford Fiesta  �12,495  20692.0       Manual  Petrol     NaN  Hatchback      ULEZ   1.0L  2019 (19 reg)
18605  Ford Fiesta  �12,495  11050.0       Manual  Petrol     NaN  Hatchback      ULEZ   1.0L  2019 (68 reg)
18604  Ford Fiesta  �12,495  30000.0       Manual  Petrol     NaN  Hatchback      ULEZ   1.0L  2019 (69 reg)
18603  Ford Fiesta  �12,495  22000.0       Manual  Petrol     2.0  Hatchback      ULEZ   1.0L  2018 (68 reg)
...            ...      ...      ...          ...     ...     ...        ...       ...    ...            ...
28883    Ford Puma  £21,111  10652.0       Manual  Petrol     NaN        SUV      ULEZ    NaN  2021 (21 reg)
29118    Ford Puma  £25,235  21359.0       Manual  Petrol     NaN        SUV      ULEZ    NaN  2021 (21 reg)
29905  Ford Ranger  £21,250  31268.0       Manual  Diesel     2.0     Pickup  Non ULEZ    NaN  2017 (17 reg)
31134  Ford Ranger  £45,000   3000.0    Automatic  Diesel     NaN     Pickup  Non ULEZ    NaN            NaN
31296  Ford Ranger  £39,663  11309.0    Automatic  Diesel     NaN     Pickup      ULEZ    NaN  2021 (71 reg)

[31389 rows x 10 columns]

In [341]:
# converting dtype to string 
df1["price"]= df1["price"].astype(str) 
# removing  
df1["price"]= df1["price"].str.replace("£", "") 
df1["price"]= df1["price"].str.replace(",", "") 
df1["price"]= df1["price"].str.replace("�", "")

<ipython-input-341-8a77f3e66ab3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["price"]= df1["price"].astype(str)
<ipython-input-341-8a77f3e66ab3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["price"]= df1["price"].str.replace("£", "")
<ipython-input-341-8a77f3e66ab3>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["price"]= df1["price"].str.replace(",", "")
<ipython-input-341-8a77f3e66ab3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["price"]= df1["price"].str.replace("�", "")

In [342]:
df1

              Name  price   mileage transmission    fuel owners       body      ULEZ engine           year
0      Ford Mondeo   1795  149026.0       Manual  Diesel    2.0     Saloon  Non ULEZ   2.2L  2005 (55 reg)
1      Ford Mondeo   2499  102000.0       Manual  Petrol    1.0  Hatchback      ULEZ   3.0L  2005 (05 reg)
2      Ford Mondeo    995  109299.0       Manual  Petrol    2.0     Saloon  Non ULEZ   1.8L  2005 (05 reg)
3      Ford Mondeo   1295   75500.0       Manual  Petrol    1.0     Estate  Non ULEZ   1.8L  2005 (55 reg)
4      Ford Mondeo   1750  157390.0       Manual  Diesel    2.0     Estate  Non ULEZ   2.2L  2005 (05 reg)
...            ...    ...       ...          ...     ...    ...        ...       ...    ...            ...
31481  Ford Ranger  32995    5513.0    Automatic  Diesel    3.0     Pickup      ULEZ   2.0L  2021 (21 reg)
31482  Ford Ranger  39594    9900.0    Automatic  Diesel    1.0     Pickup      ULEZ   2.0L  2021 (70 reg)
31483  Ford Ranger  35940   15000.0    Automatic  Diesel    1.0     Pickup      ULEZ   2.0L  2021 (70 reg)
31484  Ford Ranger  35994    6228.0    Automatic  Diesel    2.0     Pickup      ULEZ   2.0L  2021 (21 reg)
31485  Ford Ranger  32800   31500.0    Automatic  Diesel    4.0     Pickup      ULEZ   2.0L  2021 (21 reg)

[28915 rows x 10 columns]

In [343]:
df1.dtypes

Name            category
price             object
mileage          float64
transmission      object
fuel              object
owners            object
body              object
ULEZ              object
engine            object
year              object
dtype: object

In [344]:
df1["owners"].fillna("1.0", inplace = True)

/Users/ramandeeprai/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [345]:
df1

              Name  price   mileage transmission    fuel owners       body      ULEZ engine           year
0      Ford Mondeo   1795  149026.0       Manual  Diesel    2.0     Saloon  Non ULEZ   2.2L  2005 (55 reg)
1      Ford Mondeo   2499  102000.0       Manual  Petrol    1.0  Hatchback      ULEZ   3.0L  2005 (05 reg)
2      Ford Mondeo    995  109299.0       Manual  Petrol    2.0     Saloon  Non ULEZ   1.8L  2005 (05 reg)
3      Ford Mondeo   1295   75500.0       Manual  Petrol    1.0     Estate  Non ULEZ   1.8L  2005 (55 reg)
4      Ford Mondeo   1750  157390.0       Manual  Diesel    2.0     Estate  Non ULEZ   2.2L  2005 (05 reg)
...            ...    ...       ...          ...     ...    ...        ...       ...    ...            ...
31481  Ford Ranger  32995    5513.0    Automatic  Diesel    3.0     Pickup      ULEZ   2.0L  2021 (21 reg)
31482  Ford Ranger  39594    9900.0    Automatic  Diesel    1.0     Pickup      ULEZ   2.0L  2021 (70 reg)
31483  Ford Ranger  35940   15000.0    Automatic  Diesel    1.0     Pickup      ULEZ   2.0L  2021 (70 reg)
31484  Ford Ranger  35994    6228.0    Automatic  Diesel    2.0     Pickup      ULEZ   2.0L  2021 (21 reg)
31485  Ford Ranger  32800   31500.0    Automatic  Diesel    4.0     Pickup      ULEZ   2.0L  2021 (21 reg)

[28915 rows x 10 columns]

In [346]:

import numpy as np

In [347]:
df1['ULEZ']=np.where(df1['fuel']=='Electric','ULEZ',df1['ULEZ'])

df1['ULEZ']=np.where(df1['fuel']=='Petrol Plug-in Hybrid','ULEZ',df1['ULEZ'])
df1['ULEZ']=np.where(df1['fuel']=='Petrol Hybrid','ULEZ',df1['ULEZ'])

<ipython-input-347-b7b3fee15a96>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ULEZ']=np.where(df1['fuel']=='Electric','ULEZ',df1['ULEZ'])
<ipython-input-347-b7b3fee15a96>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ULEZ']=np.where(df1['fuel']=='Petrol Plug-in Hybrid','ULEZ',df1['ULEZ'])
<ipython-input-347-b7b3fee15a96>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ULEZ']=np.where(df1['fuel']=='Petrol Hybrid','ULEZ',df1['ULEZ'])

In [348]:
df1 = df1.dropna()
df1

              Name  price   mileage transmission    fuel owners       body      ULEZ engine           year
0      Ford Mondeo   1795  149026.0       Manual  Diesel    2.0     Saloon  Non ULEZ   2.2L  2005 (55 reg)
1      Ford Mondeo   2499  102000.0       Manual  Petrol    1.0  Hatchback      ULEZ   3.0L  2005 (05 reg)
2      Ford Mondeo    995  109299.0       Manual  Petrol    2.0     Saloon  Non ULEZ   1.8L  2005 (05 reg)
3      Ford Mondeo   1295   75500.0       Manual  Petrol    1.0     Estate  Non ULEZ   1.8L  2005 (55 reg)
4      Ford Mondeo   1750  157390.0       Manual  Diesel    2.0     Estate  Non ULEZ   2.2L  2005 (05 reg)
...            ...    ...       ...          ...     ...    ...        ...       ...    ...            ...
31481  Ford Ranger  32995    5513.0    Automatic  Diesel    3.0     Pickup      ULEZ   2.0L  2021 (21 reg)
31482  Ford Ranger  39594    9900.0    Automatic  Diesel    1.0     Pickup      ULEZ   2.0L  2021 (70 reg)
31483  Ford Ranger  35940   15000.0    Automatic  Diesel    1.0     Pickup      ULEZ   2.0L  2021 (70 reg)
31484  Ford Ranger  35994    6228.0    Automatic  Diesel    2.0     Pickup      ULEZ   2.0L  2021 (21 reg)
31485  Ford Ranger  32800   31500.0    Automatic  Diesel    4.0     Pickup      ULEZ   2.0L  2021 (21 reg)

[28915 rows x 10 columns]

In [349]:
df1.count()

Name            28915
price           28915
mileage         28915
transmission    28915
fuel            28915
owners          28915
body            28915
ULEZ            28915
engine          28915
year            28915
dtype: int64

In [350]:
df1 = df1[df1['mileage'].between(60, 390000)]

In [351]:
df1['price'] = df1['price'].astype('int64')

In [352]:
df1 = df1[df1['price']<60000]

In [353]:
df1['reg'] = df1['year'].str.split().str[1]
df1['reg'] = df1['reg'].str.replace('(','')
df1['year'] = df1['year'].str.split().str[0]

<ipython-input-353-1fa1d241ad6d>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df1['reg'] = df1['reg'].str.replace('(','')

In [354]:
df1

              Name  price   mileage transmission    fuel owners       body      ULEZ engine  year reg
0      Ford Mondeo   1795  149026.0       Manual  Diesel    2.0     Saloon  Non ULEZ   2.2L  2005  55
1      Ford Mondeo   2499  102000.0       Manual  Petrol    1.0  Hatchback      ULEZ   3.0L  2005  05
2      Ford Mondeo    995  109299.0       Manual  Petrol    2.0     Saloon  Non ULEZ   1.8L  2005  05
3      Ford Mondeo   1295   75500.0       Manual  Petrol    1.0     Estate  Non ULEZ   1.8L  2005  55
4      Ford Mondeo   1750  157390.0       Manual  Diesel    2.0     Estate  Non ULEZ   2.2L  2005  05
...            ...    ...       ...          ...     ...    ...        ...       ...    ...   ...  ..
31481  Ford Ranger  32995    5513.0    Automatic  Diesel    3.0     Pickup      ULEZ   2.0L  2021  21
31482  Ford Ranger  39594    9900.0    Automatic  Diesel    1.0     Pickup      ULEZ   2.0L  2021  70
31483  Ford Ranger  35940   15000.0    Automatic  Diesel    1.0     Pickup      ULEZ   2.0L  2021  70
31484  Ford Ranger  35994    6228.0    Automatic  Diesel    2.0     Pickup      ULEZ   2.0L  2021  21
31485  Ford Ranger  32800   31500.0    Automatic  Diesel    4.0     Pickup      ULEZ   2.0L  2021  21

[28909 rows x 11 columns]

In [359]:
df1['owners'] = df1['owners'].astype('float64')

In [360]:
df1["engine"]= df1["engine"].str.replace("L", "")

In [364]:
df1['year'] = df1['year'].astype('float64')

In [366]:
df1['engine'] = df1['engine'].astype('float64')

In [362]:
df1.drop(columns=['reg'], inplace = True)
df1

              Name  price   mileage transmission    fuel  owners       body      ULEZ engine  year
0      Ford Mondeo   1795  149026.0       Manual  Diesel     2.0     Saloon  Non ULEZ    2.2  2005
1      Ford Mondeo   2499  102000.0       Manual  Petrol     1.0  Hatchback      ULEZ    3.0  2005
2      Ford Mondeo    995  109299.0       Manual  Petrol     2.0     Saloon  Non ULEZ    1.8  2005
3      Ford Mondeo   1295   75500.0       Manual  Petrol     1.0     Estate  Non ULEZ    1.8  2005
4      Ford Mondeo   1750  157390.0       Manual  Diesel     2.0     Estate  Non ULEZ    2.2  2005
...            ...    ...       ...          ...     ...     ...        ...       ...    ...   ...
31481  Ford Ranger  32995    5513.0    Automatic  Diesel     3.0     Pickup      ULEZ    2.0  2021
31482  Ford Ranger  39594    9900.0    Automatic  Diesel     1.0     Pickup      ULEZ    2.0  2021
31483  Ford Ranger  35940   15000.0    Automatic  Diesel     1.0     Pickup      ULEZ    2.0  2021
31484  Ford Ranger  35994    6228.0    Automatic  Diesel     2.0     Pickup      ULEZ    2.0  2021
31485  Ford Ranger  32800   31500.0    Automatic  Diesel     4.0     Pickup      ULEZ    2.0  2021

[28909 rows x 10 columns]

In [367]:
df1.dtypes

Name            category
price              int64
mileage          float64
transmission      object
fuel              object
owners           float64
body              object
ULEZ              object
engine           float64
year             float64
dtype: object

In [368]:
df1['transmission'] = df1['transmission'].astype('category')
df1['fuel'] = df1['fuel'].astype('category')
df1['body'] = df1['body'].astype('category')
df1['ULEZ'] = df1['ULEZ'].astype('category')

In [369]:
df1.dtypes

Name            category
price              int64
mileage          float64
transmission    category
fuel            category
owners           float64
body            category
ULEZ            category
engine           float64
year             float64
dtype: object

In [370]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn import metrics

import statsmodels.api as sm
import statsmodels.tools

/Users/ramandeeprai/opt/anaconda3/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "

In [375]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split # module to split our data into train and test sets

import statsmodels.api as sm
import statsmodels.tools

In [376]:
feature_cols = list(df1.columns)
feature_cols.remove('price')

In [377]:
X = df1[feature_cols]
y = df1['price']

In [378]:
X

              Name   mileage transmission    fuel  owners       body      ULEZ  engine    year
0      Ford Mondeo  149026.0       Manual  Diesel     2.0     Saloon  Non ULEZ     2.2  2005.0
1      Ford Mondeo  102000.0       Manual  Petrol     1.0  Hatchback      ULEZ     3.0  2005.0
2      Ford Mondeo  109299.0       Manual  Petrol     2.0     Saloon  Non ULEZ     1.8  2005.0
3      Ford Mondeo   75500.0       Manual  Petrol     1.0     Estate  Non ULEZ     1.8  2005.0
4      Ford Mondeo  157390.0       Manual  Diesel     2.0     Estate  Non ULEZ     2.2  2005.0
...            ...       ...          ...     ...     ...        ...       ...     ...     ...
31481  Ford Ranger    5513.0    Automatic  Diesel     3.0     Pickup      ULEZ     2.0  2021.0
31482  Ford Ranger    9900.0    Automatic  Diesel     1.0     Pickup      ULEZ     2.0  2021.0
31483  Ford Ranger   15000.0    Automatic  Diesel     1.0     Pickup      ULEZ     2.0  2021.0
31484  Ford Ranger    6228.0    Automatic  Diesel     2.0     Pickup      ULEZ     2.0  2021.0
31485  Ford Ranger   31500.0    Automatic  Diesel     4.0     Pickup      ULEZ     2.0  2021.0

[28909 rows x 9 columns]

In [379]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 40)

In [380]:
X_train

                Name  mileage transmission    fuel  owners       body      ULEZ  engine    year
28389      Ford Puma  11141.0       Manual  Petrol     1.0        SUV      ULEZ     1.0  2020.0
17441     Ford Focus  36000.0       Manual  Petrol     1.0  Hatchback      ULEZ     1.0  2021.0
16403     Ford Focus  32024.0       Manual  Petrol     2.0  Hatchback      ULEZ     2.3  2019.0
2564   Ford Ecosport  18310.0       Manual  Petrol     1.0        SUV      ULEZ     1.0  2019.0
22124    Ford Fiesta  52000.0       Manual  Petrol     1.0  Hatchback      ULEZ     1.0  2015.0
...              ...      ...          ...     ...     ...        ...       ...     ...     ...
24433    Ford Fiesta  18477.0       Manual  Petrol     1.0  Hatchback      ULEZ     1.5  2020.0
30098    Ford Ranger  55991.0       Manual  Diesel     2.0     Pickup      ULEZ     2.2  2018.0
14765     Ford Focus  14426.0       Manual  Petrol     1.0  Hatchback      ULEZ     1.0  2018.0
14819     Ford Focus  31404.0       Manual  Diesel     1.0  Hatchback      ULEZ     1.5  2018.0
11845     Ford Focus  96710.0       Manual  Diesel     2.0  Hatchback  Non ULEZ     1.6  2013.0

[23127 rows x 9 columns]

In [382]:
y_train

28389    18450
17441    17973
16403    22489
2564     14699
22124     8695
         ...
24433    19610
30098    21987
14765    13999
14819    13500
11845     5790
Name: price, Length: 23127, dtype: int64

In [383]:
X_test

                Name   mileage transmission           fuel  owners       body      ULEZ  engine    year
31196    Ford Ranger   20149.0    Automatic         Diesel     1.0     Pickup      ULEZ     2.0  2021.0
3433   Ford Ecosport   30449.0       Manual         Petrol     1.0        SUV      ULEZ     1.0  2020.0
1589     Ford Mondeo   28504.0    Automatic  Petrol Hybrid     1.0     Saloon      ULEZ     2.0  2020.0
22410    Ford Fiesta   27139.0       Manual         Petrol     1.0  Hatchback      ULEZ     1.0  2017.0
13371     Ford Focus  121800.0    Automatic         Diesel     5.0  Hatchback      ULEZ     1.5  2016.0
...              ...       ...          ...            ...     ...        ...       ...     ...     ...
17298     Ford Focus   20716.0       Manual         Diesel     1.0  Hatchback      ULEZ     1.5  2020.0
11155     Ford Focus  109000.0       Manual         Petrol     1.0  Hatchback      ULEZ     1.6  2012.0
6491       Ford Kuga   75420.0    Automatic         Petrol     2.0        SUV      ULEZ     1.5  2017.0
3033   Ford Ecosport   13497.0       Manual         Petrol     1.0        SUV      ULEZ     1.0  2019.0
10367     Ford Focus  105024.0       Manual         Diesel     2.0     Estate  Non ULEZ     2.0  2010.0

[5782 rows x 9 columns]

In [384]:
y_test

31196    36599
3433     15385
1589     23674
22410     9499
13371     6490
         ...
17298    20000
11155     4295
6491     13683
3033     13449
10367     3995
Name: price, Length: 5782, dtype: int64

In [392]:
def feature_eng(df1):
        df1 = pd.get_dummies(df1, columns = ['fuel'], drop_first = True, prefix = 'fuel')
        df1 = pd.get_dummies(df1, columns = ['body'], drop_first = True, prefix = 'body')
        df1 = sm.add_constant(df1)
        
        return df1

In [393]:
X_train

                Name  mileage transmission    fuel  owners       body      ULEZ  engine    year
28389      Ford Puma  11141.0       Manual  Petrol     1.0        SUV      ULEZ     1.0  2020.0
17441     Ford Focus  36000.0       Manual  Petrol     1.0  Hatchback      ULEZ     1.0  2021.0
16403     Ford Focus  32024.0       Manual  Petrol     2.0  Hatchback      ULEZ     2.3  2019.0
2564   Ford Ecosport  18310.0       Manual  Petrol     1.0        SUV      ULEZ     1.0  2019.0
22124    Ford Fiesta  52000.0       Manual  Petrol     1.0  Hatchback      ULEZ     1.0  2015.0
...              ...      ...          ...     ...     ...        ...       ...     ...     ...
24433    Ford Fiesta  18477.0       Manual  Petrol     1.0  Hatchback      ULEZ     1.5  2020.0
30098    Ford Ranger  55991.0       Manual  Diesel     2.0     Pickup      ULEZ     2.2  2018.0
14765     Ford Focus  14426.0       Manual  Petrol     1.0  Hatchback      ULEZ     1.0  2018.0
14819     Ford Focus  31404.0       Manual  Diesel     1.0  Hatchback      ULEZ     1.5  2018.0
11845     Ford Focus  96710.0       Manual  Diesel     2.0  Hatchback  Non ULEZ     1.6  2013.0

[23127 rows x 9 columns]

In [394]:
X_train_eng = feature_eng(X_train)

In [395]:
X_train.head()

                Name  mileage transmission    fuel  owners       body  ULEZ  engine    year
28389      Ford Puma  11141.0       Manual  Petrol     1.0        SUV  ULEZ     1.0  2020.0
17441     Ford Focus  36000.0       Manual  Petrol     1.0  Hatchback  ULEZ     1.0  2021.0
16403     Ford Focus  32024.0       Manual  Petrol     2.0  Hatchback  ULEZ     2.3  2019.0
2564   Ford Ecosport  18310.0       Manual  Petrol     1.0        SUV  ULEZ     1.0  2019.0
22124    Ford Fiesta  52000.0       Manual  Petrol     1.0  Hatchback  ULEZ     1.0  2015.0

In [399]:
feature_cols = ['mileage', 'owners', 'engine', 'year']

## 
lin_reg = sm.OLS(y_train, X_train[feature_cols])
results = lin_reg.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.910
Model:                            OLS   Adj. R-squared (uncentered):              0.910
Method:                 Least Squares   F-statistic:                          5.862e+04
Date:                Wed, 26 Oct 2022   Prob (F-statistic):                        0.00
Time:                        10:15:33   Log-Likelihood:                     -2.2797e+05
No. Observations:               23127   AIC:                                  4.559e+05
Df Residuals:                   23123   BIC:                                  4.560e+05
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
mileage       -0.1724      0.001   -167.527      0.000      -0.174      -0.170
owners      -881.1539     33.293    -26.467      0.000    -946.410    -815.898
engine      6794.5074     60.940    111.495      0.000    6675.061    6913.954
year           6.1273      0.049    125.679      0.000       6.032       6.223
==============================================================================
Omnibus:                     3895.687   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11460.568
Skew:                           0.889   Prob(JB):                         0.00
Kurtosis:                       5.955   Cond. No.                     1.12e+05
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.12e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [400]:
X_train['y_pred'] = results.predict(X_train[feature_cols])

rmse = statsmodels.tools.eval_measures.rmse(y_train, X_train['y_pred'])

print(rmse)

4621.123468128722

<ipython-input-400-483c717c62e1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['y_pred'] = results.predict(X_train[feature_cols])